### ISSUE TITLE
Documentation link broken

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/maxent#1]
Dear all, the documentation link in the readme is broken for me. Best, Hugo

**Comment by gkraberger** [comment]
Hi Hugo,

yes, we are aware of that.
Manuel asked @Wentzell to set up Jenkins for us, which would then generate the website.
Nils, please tell me if I can do anything to help you in order to speed up the process.

Cheers
Gernot

**Comment by gkraberger** [comment]
Thanks, @dylex, for getting that to work. Doc is now online.
