### ISSUE TITLE
Continuation of self-energies

### ISSUE THREAD

**Issue by Reyhanehe** [TRIQS/maxent#10]
Dear All
Hi
I run the Continuation of self-energies for SrVO3 compound using maxentropy method. I used the script for my work that is the same of Sr2RuO4 script which are implemented in maxantropy method in triqs code. but in my script I set dc-energy to -0.004687675298281441 that obtained from my LDA+DMFT calculation considering spinpolarise interaction and also I changed the window energy to -7 to 7 eV.
But After this executation I have the below result for Sigma for example for block-names up_1:
[[[ 0.98501606-0.30395847j]]

 [[ 1.11531127-0.40518312j]]

 [[ 1.20902543-0.44647038j]]
...
...

 [[ 0.70354585-0.38301626j]]

 [[ 0.68045362-0.40761561j]]

 [[ 0.65748259-0.43339452j]]

 [[ 0.63468014-0.46039073j]]

 [[ 0.61209789-0.48864141j]]

 [[ 0.58979190-0.51818283j]]

 [[ 0.56782290-0.54905004j]]]
 
could you please help me to knowing that how I can obtain the true results for my calculation?
thank you very much
Reyhaneh

**Comment by Reyhanehe** [comment]
Excuse me
I give the below  results for Sigma in this block-names:
"
[[[ 0.98501606-0.30395847j]]

 [[ 1.11531127-0.40518312j]]

 [[ 1.20902543-0.44647038j]]

 ..., 
 [[ 2.73422058-0.03647344j]]

 [[ 2.74085167-0.03358869j]]

 [[ 2.75062776-0.02611433j]]]
" 

while these should be:
"
[[[ 2.07535437-0.1951497j ]]

 [[ 2.06835777-0.18792663j]]

 [[ 2.06122282-0.18084569j]]

 [[ 2.05395135-0.17390563j]]

 [[ 2.04654498-0.16710522j]]

 [[ 2.03900515-0.16044327j]]

 [[ 2.03133313-0.15391866j]]

 [[ 2.02353002-0.14753029j]]

 [[ 2.01559673-0.14127713j]]

 [[ 2.00753405-0.13515823j]]

 [[ 1.99934257-0.12917269j]]

 [[ 1.99102275-0.12331966j]]

 [[ 1.98257490-0.11759841j]]

 [[ 1.97399918-0.11200824j]]

 [[ 1.96529560-0.10654857j]]

 [[ 1.95646404-0.1012189j ]]

 [[ 1.94750425-0.0960188j ]]

 [[ 1.93841584-0.09094795j]]

 [[ 1.92919829-0.08600613j]]

 [[ 1.91985097-0.08119321j]]

 [[ 1.91037309-0.07650919j]]

 [[ 1.90076378-0.07195415j]]

 [[ 1.89102204-0.06752831j]]

 [[ 1.88114673-0.06323199j]]

 [[ 1.87113663-0.05906564j]]

 [[ 1.86099039-0.05502983j]]

 [[ 1.85070655-0.05112529j]]

 [[ 1.84028355-0.04735284j]]

 [[ 1.82971972-0.04371348j]]

 [[ 1.81901329-0.04020835j]]

 [[ 1.80816238-0.03683871j]]

 [[ 1.79716502-0.03360602j]]

 [[ 1.78601913-0.03051188j]]

 [[ 1.77472256-0.02755806j]]

 [[ 1.76327303-0.02474652j]]

 [[ 1.75166819-0.02207937j]]

 [[ 1.73990559-0.01955894j]]

 [[ 1.72798271-0.01718776j]]

 [[ 1.71589691-0.01496853j]]

 [[ 1.70364551-0.01290419j]]

 [[ 1.69122571-0.01099789j]]

 [[ 1.67863466-0.00925303j]]

 [[ 1.66586942-0.00767321j]]

 [[ 1.65292698-0.00626232j]]

 [[ 1.63980427-0.00502449j]]

 [[ 1.62649814-0.00396411j]]

 ...

 [[ 0.68045362-0.40761561j]]

 [[ 0.65748259-0.43339452j]]

 [[ 0.63468014-0.46039073j]]

 [[ 0.61209789-0.48864141j]]

 [[ 0.58979190-0.51818283j]]

 [[ 0.56782290-0.54905004j]]]
"

**Comment by mzingl** [comment]
I have no idea what you mean by 'true' results.
This is the issue list for maxent. You can use maxent to continue Sigma_w to Sigma_iw.
Your result of Sigma_w will depend on what you put in as Sigma_iw.
If your Sigma_w doesn't look like what you would expect than you are either using the code
incorrectly or your Sigma_iw is flawed.

**Comment by Reyhanehe** [comment]
Dear Mzingl
Thanks a lot
So I checked my calculation again. 
Sincerely yours
