### ISSUE TITLE
Error during analytic continuation for real-frequency self-energy

### ISSUE THREAD

**Issue by cmtcl18** [TRIQS/maxent#13]
Dear all,
I want to calculate the real frequency self energy for calculating the DOS and the band structure of SrVO3. I have installed MAXENT successfully.  I use the following commands to get the real frequency.

from pytriqs.archive import HDFArchive
# load G_tau from h5
h5 = HDFArchive('SrVO3.h5','r')
# this will show you the content
print h5['DMFT_results']

G_tau = h5['DMFT_results']['it_15']['Gimp_tau_0']

tm_bryan = TauMaxEnt(cost_function='bryan', probability='normal')
# this will set the just loaded Gtau, this is just the spin up block and the first orbital!
tm_bryan.set_G_tau(G_tau['up_0'][0,0].real)

tm_bryan.omega = HyperbolicOmegaMesh(omega_min=-15, omega_max=15, n_points=400)
# this is also just a suggestion, play around with the alpha values
tm_bryan.alpha_mesh = LogAlphaMesh(alpha_min=5e-5, alpha_max=500, n_points=20)
# careful about setting the error!
tm_bryan.set_error(1.e-2)

# run it
tm_bryan_res = tm_bryan.run()

But I am getting the following error.
Traceback (most recent call last):
  File "new2.py", line 5, in <module>
    print h5['DMFT_results']
  File "/home/jatin/triqs/install/lib/python2.7/site-packages/pytriqs/archive/hdf_archive.py", line 228, in __getitem__
    return self.__getitem1__(key,self._reconstruct_python_objects)
  File "/home/jatin/triqs/install/lib/python2.7/site-packages/pytriqs/archive/hdf_archive.py", line 235, in __getitem1__
    if key not in self  : raise KeyError, "Key %s does not exist."%key
KeyError: 'Key DMFT_results does not exist.'

Any suggestion is appreciated.

Best Regards,
CMTCL

~

**Comment by mzingl** [comment]
This means that you don't have a group DMFT_results in your h5 file.
You just need to load your G(tau), which will depends on how you stored it in the h5 file,
and then pass it on to maxent with set_G_tau.

**Comment by mzingl** [comment]
How should I look at your files if they sit in your home directory?
That's impossible - only hackers can do that.

Again, the only thing you need to do is store S.G_tau to h5 and then load it again.
There is not much more to say.
