### ISSUE TITLE
Crash for matrix-valued self energy

### ISSUE THREAD

**Issue by ethmerkel** [TRIQS/maxent#16]
I have an issue with the matrix-valued self energy, which might be the same problem as in issue #11.
In the file maxent_util.py in line 103, the code crashes because it tries to assign a numpy array of length np_interp_A (RHS) to a numpy array of length n_w (LHS).

The error produced is `ValueError: could not broadcast input array from shape (2000) into shape (100)`

**Comment by mzingl** [comment]
Hi,
indeed, that is a bug.
And the unit test doesn't catch it, because there we use the same number of points...
Thanks for pointing it out. I'll fix it.
Best, Manuel

**Comment by ethmerkel** [comment]
Hi Manuel,
Thanks for working on it!
Best,
Max

**Comment by mzingl** [comment]
Hi,

I had a look at the issue.
Can you try to run your code again with the newest commit on the master branch
and then let me know if it works?

Best, Manuel

**Comment by ethmerkel** [comment]
Hi,
It runs through now. But I got this warning `/triqs/lib/python2.7/site-packages/triqs_maxent/maxent_util.py:105: ComplexWarning: Casting complex values to real discards the imaginary part
  w_points, A_w[i, j, :])` and the resulting Sigma(omega) is NaN.
I think for the self energy we need the imaginary part of the spectral function, right? Which might be fixed by using `dtype=complex` when initializing `A_temp`

**Comment by mzingl** [comment]
Hi,
thank you for pointing this out. Can you try again?

Best, Manuel

**Comment by ethmerkel** [comment]
Hi Manuel,
Now I works. Thank you for fixing it so quickly!

I also realized that the NaN values for Sigma actually came from the fact that I still had to manually enforce the Hermitian-ness of the maxent result, i.e. replace the off-diagonal NaN values in the result by the corresponding conjugate transposed element.
Best, Max
