### ISSUE TITLE
Error during analytical continuation

### ISSUE THREAD

**Issue by cmtcl18** [TRIQS/maxent#18]
Dear All,
Initially I installed TRIQS, DFTTools, CTHYB, MAXENT using ` ubuntu debian packages`. Due to getting some environmental problem I again installed TRIQS, DFTTools, CTHYB using conda,  but MAXENT is installed using ` ubuntu debian packages`. I am running a test calculation for `LaMnO3`.
I am getting the following error.  I have used the following python script.
[maxent.zip](https://github.com/TRIQS/maxent/files/4499761/maxent.zip)

> Traceback (most recent call last):
  File "maxent.py", line 3, in <module>
    from triqs_maxent import *
ImportError: No module named triqs_maxent
 
The same error is also appearing for analytical continuation of `SrVO3`, which was run with out any error, when I installed TRIQS, DFTTools, CTHYB, MAXENT using debian packages.

Honestly I want to know whether it is related to `anaconda`. I already tried to debug the error as python error. If it is really related to python error, please let me know, I will close the issue and debug the error myself.

Warm Regards
CMTCL

**Comment by mzingl** [comment]
Yes, the reason is that triqs maxent is not installed in your conda environment. We don't have a conda package for triqs maxent. @Wentzell do we plan to provide one for maxent?

It might be possible to install maxent in your conda environment from source or link outside packages.  I'm not using conda, so I can't really help with that.

**Comment by Wentzell** [comment]
Dear @cmtcl18,

Under Ubuntu please use the Debian packages that we provide.
It is further not recommended to mix Anaconda and Debian package installations.
Please use **only one** packaging solution at a time.

There is no plan to add the maxent package to conda in the short term.
We are gathering some experience with the conda packages for the main applications
dft_tools, cthyb and tprf at the moment.

**Comment by Wentzell** [comment]
> It might be possible to install maxent in your conda environment from source or link outside packages. I'm not using conda, so I can't really help with that.

This is indeed a solution for a pure Anaconda environment. In that case you would first make sure
to load the triqs installation of anaconda with

```
source path_to_conda/share/triqsvars.sh
```

and then [install TRIQS/maxent from source](https://triqs.github.io/maxent/master/install.html#compiling-triqs-maxent-from-source)

**Comment by cmtcl18** [comment]
Thank you for your response dear Manuel and Wentzell. 
I followed the above procedure and installed TRIQS/maxent. 
While I convert the imaginary frequency Sigma_iw to real frequency Sigma_w, the following error is appearing.

> Starting run with 2 MPI rank(s) at : 2020-04-22 18:46:37.621921
Cannot open the HDF file LaMnO3_maxent.h5
Traceback (most recent call last):
  File "maxent2.py", line 27, in <module>
    with HDFArchive('LaMnO3_maxent.h5', 'a') as ar:
  File "/home/hp/miniconda2/lib/python2.7/site-packages/pytriqs/archive/hdf_archive.py", line 389, in __init__
    self._init_root( LocalFileName, open_flag)
  File "/home/hp/miniconda2/lib/python2.7/site-packages/pytriqs/archive/hdf_archive_basic_layer_h5py.py", line 38, in _init_root
    fich = h5py.File(LocalFileName, open_flag)
  File "/home/hp/miniconda2/lib/python2.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/home/hp/miniconda2/lib/python2.7/site-packages/h5py/_hl/files.py", line 187, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 108, in h5py.h5f.create
IOError: Unable to create file (unable to open file: name = 'LaMnO3_maxent.h5', errno = 17, error message = 'File exists', flags = 15, o_flags = c2)
Exception AttributeError: "HDFArchive instance has no attribute '_group'" in <object repr() failed> ignored

In fact I have the LaMnO3_maxent.h5 file already but it's throwing the error.

Can you suggest, why this error is appearing  even though I have the case_maxent.h5 file.

**Comment by mzingl** [comment]
Are you reading the h5 files on all cores? If you are running on multiple cores with mpi, then
you should be using `if mpi.is_master_node():` to load from h5 only on the master.
After that you will need to broadcast your data with `mpi.bcast` to all other cores.

**Comment by mzingl** [comment]
Is this still an open issues?

**Comment by cmtcl18** [comment]
Hi Manuel,
The issue is resolved. 
Would you mind to suggest  to debug the ` segfault ` errors that I have sent in `DFTTools ` issue.

I am closing this discussion here.
