### ISSUE TITLE
Failed Test set_G_tau_complex_matrix

### ISSUE THREAD

**Issue by malte-schueler** [TRIQS/maxent#19]
Hi!
I found that the test set_G_tau_complex_matrix fails. After inspecting the testing output it seems like a minor issue of rounding errors but I thought I let you know. Here is the output of the test:

```
AssertionError:
Arrays are not almost equal to 13 decimals

Mismatched elements: 5512 / 6007 (91.8%)
Max absolute difference: 1.35742084e-10
Max relative difference: 8.19991319e-10
 x: array([-0.3111849165918, -0.4986941030354, -0.5142547362803, ...,
       -0.5423565362871, -0.5084568296734, -0.2299699869492])
 y: array([-0.3111849165917, -0.4986941030063, -0.5142547362512, ...,
       -0.542356536258 , -0.5084568297025, -0.2299699869492])
```

I am using maxent commit 734bc56b9aa504bbdace7068a9da3d17eb488989 and triqs commit 5514b6ff7d9ff18eff9ae21572fc43c2e74f5bd6
I am installing on Ubuntu 18.04 with python from anaconda.
This is the output of cmake: https://gist.github.com/malte-schueler/263acf2dd43bb8e17c05fcdbd7d2243b

**Comment by mzingl** [comment]
Hi Malte!

Yes, the accuracy of some tests in TRIQS/maxent is quite strict. I have seen this test fail 
myself several times. I lowered the accuracy now to 1e-9 with commit d5d78560, which is
still fine. Thanks for reporting.

Best, Manuel

**Comment by malte-schueler** [comment]
Thanks Manuel! I'll close the issue.
