### ISSUE TITLE
error with triqs3

### ISSUE THREAD

**Issue by Reyhanehe** [TRIQS/maxent#21]
Dear all
Hi
I installed  triqs code with version 3 on my computer. when I want install the maxent program from the "https://triqs.github.io/maxent/latest/install.html" website, after the "make" command I have not any thing in the command line . then, when I used the "make test" command  all test were failed with the error "make: *** [Makefile:95: test] Error 8" .  can you help me about this problem? 
Thank you very much
Reyhaneh

**Comment by Reyhanehe** [comment]
I copy my error in below:
"**reyhan@cm7 maxent.build]$ make
[reyhan@cm7 maxent.build]$ make test
Running tests...
Test project /home/reyhan/triqs/triqs/maxent.build
      Start  1: omega_meshes
 1/33 Test  #1: omega_meshes .....................***Failed    1.16 sec
      Start  2: minimizer_cubefun
 2/33 Test  #2: minimizer_cubefun ................***Failed    1.19 sec
      Start  3: minimizer_circlefun
 3/33 Test  #3: minimizer_circlefun ..............***Failed    1.20 sec
      Start  4: minimizer_sin
 4/33 Test  #4: minimizer_sin ....................***Failed    1.20 sec
      Start  5: cached_view
 5/33 Test  #5: cached_view ......................***Failed    1.29 sec
      Start  6: plus_minus_entropy
 6/33 Test  #6: plus_minus_entropy ...............***Failed    1.24 sec
      Start  7: maxent_cost_function_lazy
 7/33 Test  #7: maxent_cost_function_lazy ........***Failed    1.25 sec
      Start  8: maxent_cost_function_d
 8/33 Test  #8: maxent_cost_function_d ...........***Failed    1.13 sec
      Start  9: functions_different_grid
 9/33 Test  #9: functions_different_grid .........***Failed    1.17 sec
      Start 10: tau_kernel
10/33 Test #10: tau_kernel .......................***Failed    1.18 sec
      Start 11: alpha_meshes
11/33 Test #11: alpha_meshes .....................***Failed    1.16 sec
      Start 12: default_models
12/33 Test #12: default_models ...................***Failed    1.20 sec
      Start 13: logtaker
13/33 Test #13: logtaker .........................***Failed    1.25 sec
      Start 14: matrix_maxent_result
14/33 Test #14: matrix_maxent_result .............***Failed    1.14 sec
      Start 15: maxent_loop
15/33 Test #15: maxent_loop ......................***Failed    1.21 sec
      Start 16: tau_maxent
16/33 Test #16: tau_maxent .......................***Failed    1.19 sec
      Start 17: bryan_cost_function
17/33 Test #17: bryan_cost_function ..............***Failed    1.15 sec
      Start 18: huge_alpha
18/33 Test #18: huge_alpha .......................***Failed    1.15 sec
      Start 19: cov
19/33 Test #19: cov ..............................***Failed    1.23 sec
      Start 20: elementwise_maxent
20/33 Test #20: elementwise_maxent ...............***Failed    1.24 sec
      Start 21: elementwise_set_G
21/33 Test #21: elementwise_set_G ................***Failed    1.28 sec
      Start 22: pickle_maxent_result
22/33 Test #22: pickle_maxent_result .............***Failed    1.14 sec
      Start 23: complex_A
23/33 Test #23: complex_A ........................***Failed    1.25 sec
      Start 24: maxent_result
24/33 Test #24: maxent_result ....................***Failed    1.25 sec
      Start 25: analyzers
25/33 Test #25: analyzers ........................***Failed    1.25 sec
      Start 26: set_G_tau
26/33 Test #26: set_G_tau ........................***Failed    1.20 sec
      Start 27: set_G_tau_complex_matrix
27/33 Test #27: set_G_tau_complex_matrix .........***Failed    1.21 sec
      Start 28: tau_maxent_off
28/33 Test #28: tau_maxent_off ...................***Failed    1.28 sec
      Start 29: srvo3_mesh_and_ALPS
29/33 Test #29: srvo3_mesh_and_ALPS ..............***Failed    1.14 sec
      Start 30: complex_elementwise_maxent
30/33 Test #30: complex_elementwise_maxent .......***Failed    1.25 sec
      Start 31: G_w_from_A_w
31/33 Test #31: G_w_from_A_w .....................***Failed    1.25 sec
      Start 32: G_tau_from_A_w
32/33 Test #32: G_tau_from_A_w ...................***Failed    1.19 sec
      Start 33: sigma_continuation
33/33 Test #33: sigma_continuation ...............***Failed    1.21 sec

0% tests passed, 33 tests failed out of 33

Total Test time (real) =  40.10 sec**
"

**Comment by the-hampel** [comment]
Hi Reyhanehe,
that looks as if maxent is not build, then it is obvious that the test will not pass. Could you please show the output from your `cmake` command, running before make? 

Is there a reason why you cannot use the prebuild packaged version of maxent? See https://triqs.github.io/maxent/latest/install.html for further information.

**Comment by Reyhanehe** [comment]
Dear Hampel 
Thanks a lot for your immediately response to me. I have below output after "cmake" command:

"[reyhan@cm7 maxent.build]$ cmake ../maxent.src
-- -------- BUILD-TYPE: Release -------------
-- The CXX compiler identification is GNU 7.3.1
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Cpp2PyConfig.cmake with version 2.0.0, hash = ……., root = /triqs.install
-- Found itertools-config.cmake with version 1.0.0, hash = …..., root =/triqs.install
-- Found mpi-config.cmake with version 1.0.0, hash = …..., root = /triqs.install
-- Found h5-config.cmake with version 1.0.0, hash = …..., root =/triqs.install
-- Found TRIQSConfig.cmake with version 3.0.0, hash = ...…,root =/triqs.install
-- --------- Installing as TRIQS 3.0.0 package ---------
--  No install prefix given (or invalid). Defaulting to TRIQS_ROOT
-- -------- CMAKE_INSTALL_PREFIX:/triqs.install -------------
-- 'make install' will install maxent as python package to: /triqs.install/lib/python3.6/site-packages/triqs_maxent
-- 'make install' will install bin files to: /triqs.install/bin
-- Git hash: …...
-- -------- Preparing tests  -------------
-- Configuring done
-- Generating done
-- Build files have been written to:/maxent.build
"
noticeable that after "hash" In this configurations I have different numbers that I did not write them here and use ".…" instead of them.
about "https://triqs.github.io/maxent/latest/install.html" : yes, I used this site for installing the maxent on my computer but for triqs with version 3.0.0, It does not work .. 
have you any idea about this?
thank you so much

**Comment by the-hampel** [comment]
Okay that looks good. Can you verify that the triqs 3 installation works in principle, i.e. can you run in the same terminal python3 and successfully import something from triqs: 
```
from triqs.gf import *
```
does that work? 

Then, I do not understand why you do not see any output from `make`. Can you post the output from the `make` command please? If there is nothing, it also did nothing, which is not okay. 

Third, could you after running `make` please run: `ctest -V -R omega_meshes` and show the output.

**Comment by Reyhanehe** [comment]
Dear Hampel
I am suprized now!! because after compiling triqs code I had not any error and this code is compiled correctly.. but now when I want import some module from it I have error such as below:
" reyhan@cm7 ~]$ python3.6
Python 3.6.5 (default, Apr  4 2018, 15:09:05) 
[GCC 7.3.1 20180130 (Red Hat 7.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from triqs.gf import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'triqs.gf'
"
I dont know why this problem is occured because for triqs with version 2 I had not such problems.

**Comment by the-hampel** [comment]
okay - that might be the problem here. Can you make sure that your `$PYTHONPATH` looks correct? More specifically it should like this: `/triqs.install/lib/python3.6/site-packages/`. Please check with `echo $PYTHONPATH` . If it is missing you need to source first the correct environment. triqs should prepare that for you. Look for a bash script called `triqsvars.sh` in `/triqs.install/share/triqs` and source it: `source /triqs.install/share/triqs/triqsvars.sh` and check again if it works.

**Comment by Reyhanehe** [comment]
Dear Hampel
when I echo $PYTHONPATH I have :
"[reyhan@cm7 ~]$ source /home/reyhan/triqs/triqs/triqs.install/share/triqsvars.sh
[reyhan@cm7 ~]$ echo $PYTHONPATH 
/home/reyhan/triqs/triqs/triqs.install/lib/python3.6/site-packages:/usr/bin/phonopy
"
It seems to be correct.. It is right?
than

**Comment by Reyhanehe** [comment]
I also check import "triqs.gf" and It could be successfully import as follows:
"
python 3.6.5 (default, Apr  4 2018, 15:09:05) 
[GCC 7.3.1 20180130 (Red Hat 7.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from triqs.gf import *
>>> 
"

**Comment by Reyhanehe** [comment]
I also check import "triqs.gf" and It could be successfully import as follows:
"
python 3.6.5 (default, Apr  4 2018, 15:09:05) 
[GCC 7.3.1 20180130 (Red Hat 7.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from triqs.gf import *
>>> 
"

**Comment by Reyhanehe** [comment]
I also check import "triqs.gf" and It could be successfully import as follows:
"
python 3.6.5 (default, Apr  4 2018, 15:09:05) 
[GCC 7.3.1 20180130 (Red Hat 7.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from triqs.gf import *
>>> 
"

**Comment by Reyhanehe** [comment]
I also check import "triqs.gf" and It could be successfully import as follows:
"
python 3.6.5 (default, Apr  4 2018, 15:09:05) 
[GCC 7.3.1 20180130 (Red Hat 7.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from triqs.gf import *
>>> 
"

**Comment by Reyhanehe** [comment]
Dear Hampel 
I can install maxent package successfully and without any error and warning now.
my problem was resolved by "source /triqs.install/share/triqs/triqsvars.sh" in command line . before I wrote this sentence in my "bashrc" but It seems not work when it was in my bashrc!! 
Thanks to you for your best and useful comments on my problem:)
Reyhaneh

**Comment by the-hampel** [comment]
Perfect! Could you please then close this issue if everything is resolved? Thanks!

**Comment by Reyhanehe** [comment]
Sure.
Sincerely yours 
Reyhaneh
