### ISSUE TITLE
s_w from s_iw

### ISSUE THREAD

**Issue by Reyhanehe** [TRIQS/maxent#22]
Dear all
Hi
I want plot the density of states of "Sr2RuO4" using DFT+DMFT method by triqs (with version 3.0.0) and WIEN2k codes . After a full charge self consistency , for calculation of real part of Sigma I used maxent method. for this purpose I used below scripts:

`from triqs_maxent import *
from h5 import *
# Load self-energy from h5-file
with HDFArchive('Sr2RuO4_b37.h5', 'r') as ar:
    S_iw = ar['S_iw']
    dc = ar['dc']
# Initialize SigmaContinuator, we use the
# double counting (dc) as constant shift c.
isc = InversionSigmaContinuator(S_iw, dc)
# run TauMaxEnt for each block and collect results
# in dict res.
res = {}
for name, gaux_iw in isc.Gaux_iw:
    tm = TauMaxEnt()
    tm.set_G_iw(gaux_iw)
    tm.set_error(1e-4)
    tm.omega = HyperbolicOmegaMesh(omega_min=-10, omega_max=10, n_points=500)
    tm.alpha_mesh = LogAlphaMesh(alpha_min=1e-2, alpha_max=1e2, n_points=30)
    res[name] = tm.run()
# save results and the SigmaContinuator to h5-file
with HDFArchive('Sr2RuO4_b37.h5', 'a') as ar:
    for key in res:
        ar['maxent_result_' + key] = res[key].data
    ar['isc'] = isc`

and: 

`from triqs_maxent import *
from h5 import *
from triqs.plot.mpl_interface import oplot
# load res and SigmaContinuator from h5-file
res = {}
with HDFArchive('Sr2RuO4_b37.h5', 'r') as ar:
    S_iw = ar['S_iw']
    for key in S_iw.indices:
        res[key] = ar['maxent_result_' + key]
    isc = ar['isc']
# get S_w from the auxilliary spectral function Aaux_w
Aaux_w = {}
w = res['up_0'].omega
for key in res:
    Aaux_w[key] = res[key].analyzer_results['LineFitAnalyzer']['A_out']
isc.set_Gaux_w_from_Aaux_w(Aaux_w, w, np_interp_A=10000,
                           np_omega=4000, w_min=-1.0, w_max=1.0)
# save SigmaContinuator again (now it contains S_w)
with HDFArchive('Sr2RuO4_b37.h5', 'a') as ar:
    ar['isc'] = isc
# check linfit and plot S_w
plt.figure()
plt.subplot(1, 2, 1)
for key in res:
    res[key].analyzer_results['LineFitAnalyzer'].plot_linefit()
plt.ylim(1e1, 1e4)
plt.subplot(1, 2, 2)
oplot(isc.S_w['up_0'], mode='I', label='maxent xy', lw=3)
oplot(isc.S_w['up_1'], mode='I', label='maxent xz', lw=3)
plt.ylabel(r'$\Sigma(\omega)$')
plt.xlim(-0.75, 0.75)
plt.ylim(-0.4, 0.0)`

I could run this scripts without any error but when I want use S_W for post processing by the following script:

`from triqs_dft_tools.sumk_dft import *
with HDFArchive('Sr2RuO4_b37.h5', 'r') as ar:
      SigmaReFreq = ar['dmft_output']['Sigma_w']
SK.set_Sigma([SigmaReFreq])
chemical_potential, dc_imp, dc_energ = SK.load(['chemical_potential','dc_imp','dc_energ'])
SK.set_mu(chemical_potential)
SK.set_dc(dc_imp,dc_energ)`

I have an error that:

`tarting run with 1 MPI rank(s) at : 2020-12-23 01:07:00.014444
Traceback (most recent call last):
  File "7.py", line 3, in <module>
    SigmaReFreq = ar['dmft_output']['Sigma_w']
  File "/home/reyhan/triqs/triqs/triqs.install/lib/python3.6/site-packages/h5/archive.py", line 205, in __getitem__
    return self.__getitem1__(key,self._reconstruct_python_objects)
  File "/home/reyhan/triqs/triqs/triqs.install/lib/python3.6/site-packages/h5/archive.py", line 211, in __getitem1__
    raise KeyError("Key %s does not exist."%key)
KeyError: 'Key dmft_output does not exist.'`
  I check my "case.h5" and see that it has below  content:
"['S_iw', 'dc', 'isc', 'maxent_result_down_0', 'maxent_result_down_1', 'maxent_result_down_2', 'maxent_result_up_0', 'maxent_result_up_1', 'maxent_result_up_2']>"

Have you any idea about my problem?
Sincerely yours
Reyhaneh

**Comment by the-hampel** [comment]
Hi,
I say that again. Can you please format your code! This is unreadable. There is a preview button when writing an issue. Please check carefully, if your source code is displayed properly. 

The problem is that in your h5 file that you are loading, there is no object called 'dmft_output' . You have to create first that object and store in the h5 the `S_w` object. So far you only stored the Maxent results as `isc` You first need to create a full `S_w` object, and store it in the h5 file you are loading.

**Comment by Reyhanehe** [comment]
Dear Hampel
Thank a lot for your comment. 
Excuseme .I used "insert code" icon to paste my scripts but I dont know why these can not be pasted in the correct format.
Yes,I have S_w in "isc", so I used the following line in my previoue script:
`Archive('Sr2RuO4_b37.h5', 'r') as ar:
      SigmaReFreq = ar['isc']['S_w']
SK.set_Sigma([SigmaReFreq])
`
But It has following error and can not be done.

`Starting run with 1 MPI rank(s) at : 2020-12-23 11:48:33.280112
Loading failed: No dft_input subgroup in hdf5!
Traceback (most recent call last):
  File "7.py", line 4, in <module>
    SK = SumkDFTTools(hdf_file = filename + '.h5')
  File "/home/reyhan/triqs/triqs/triqs.install/lib/python3.6/site-packages/triqs_dft_tools/sumk_dft_tools.py", line 50, in __init__
    misc_data=misc_data)
  File "/home/reyhan/triqs/triqs/triqs.install/lib/python3.6/site-packages/triqs_dft_tools/sumk_dft.py", line 108, in __init__
    raise ValueError('ERROR: One or more necessary SumK input properties have not been found in the given h5 archive:',self.values_not_read)
ValueError: ('ERROR: One or more necessary SumK input properties have not been found in the given h5 archive:', ['energy_unit', 'n_k', 'k_dep_projection', 'SP', 'SO', 'charge_below', 'density_required', 'symm_op', 'n_shells', 'shells', 'n_corr_shells', 'corr_shells', 'use_rotations', 'rot_mat', 'rot_mat_time_inv', 'n_reps', 'dim_reps', 'T', 'n_orbitals', 'proj_mat', 'bz_weights', 'hopping', 'n_inequiv_shells', 'corr_to_inequiv', 'inequiv_to_corr'])
`

can you please help me to resolve this problem?
Best,
Reyhaneh

**Comment by the-hampel** [comment]
Hi, 
no you mixed something up. The line for loading Sigma_w looks okay now. However, `SK = SumkDFTTools(hdf_file = filename + '.h5')` seems to point to the wrong h5 file. You tried to use the file from maxent, but this one has no DMFT input from DFT. So for loading Sigma_w use the h5 file from maxent, but to create the Sumk object you need to use your original h5 archive from Wien2k. I hope that helps. 

P.S. I guess your insert code does not work because at some point your script contains symbols that are interpreted by github as markdown. Try to manually paste your code instead. That should work better. For longer pieces of code use ``` marks before and after the code like this: 
```
code here
```

**Comment by Reyhanehe** [comment]
Dear Hampel
Hi
thanks a lot for your best comment on my issue. But when I do not use the `SK = SumkDFTTools(hdf_file = filename + '.h5')` and use only following script :

`from triqs_dft_tools.sumk_dft_tools import *
with HDFArchive('Sr2RuO4_b37.h5', 'r') as ar:
      SigmaReFreq = ar['isc']['S_w']
SK.set_Sigma([SigmaReFreq])
chemical_potential, dc_imp, dc_energ = SK.load(['chemical_potential','dc_imp','dc_energ'])
SK.set_mu(chemical_potential)
SK.set_dc(dc_imp,dc_energ)
`
I have below error:

`Starting run with 1 MPI rank(s) at : 2020-12-24 00:41:41.292682
Warning : The hdf5 format InversionSigmaContinuator is not recognized. Returning as a group. Hint : did you forgot to import this python class ?
Traceback (most recent call last):
  File "7.py", line 7, in <module>
    SK.set_Sigma([SigmaReFreq])
NameError: name 'SK' is not defined
`
Can you please help me to solving this subject?
Sincerely yours 
Reyhaneh

**Comment by the-hampel** [comment]
That was not exactly what I suggested. You need to create a Sumk object via `SK = SumkDFTTools(...)` , but you have to give here as h5 filename the one with the input for DFTTools. This must be an h5 archive with the `dft_input` structure. I suggest that you try to familiarize yourself with the structure of your h5 files. Python also tells you this, saying that it does not know the variable name `SK`, which should tell you that you need to create it first. Then you can load from the other h5 archive with the `S_w` object, and set this as Sigma. 

Moreover Python now complains that you did not load the `InversionSigmaContinuator` class from MaxEnt. You need to import this module from MaxEnt first and then try to load it from the h5 archive.

**Comment by Reyhanehe** [comment]
Dear Hampel
Thanks a lot
So now I close this issue and try to solve it using your useful idea and if I have errors then I share my questions again.
Best regards
Reyhaneh
