### ISSUE TITLE
real-frequency of self-energy

### ISSUE THREAD

**Issue by Reyhanehe** [TRIQS/maxent#5]
Dear all
Hi
I want to calculate post processing information by using DFT+DMFT.
I know that I shoud have the rael frequency self energy by using maxent.
I read about it. But can you help me to done it?
means can any one tell me the steps for doing it?
thanks for any help to me

**Comment by the-hampel** [comment]
Good Morning Reyhanehe,
did you check out the documentation? https://triqs.github.io/maxent/master/guide/srvo3.html 
Did you tried to run these examples? They already show pretty detailed how to run maxent and to get nice spectral functions. Are you stuck at a specific point? 

Best,
Alex

**Comment by Reyhanehe** [comment]
Dear Alex
Thanks for your comment
Yes I run it , But when I run Tau maxent for srvo3 I have this error that "srvo3-Gtau.dat" is not recognized.
I did not know the meaning of this error because I think srvo3-Gtau.dat is the file that the information of my executatiin shoud save on it.right?
If you can help me ,you help me a lot for solving my problem
Reyhaneh

**Comment by the-hampel** [comment]
Hi,
ah no - I assume you did your calculation and the data is stored inside of a h5 archive? Then you need to access the data as follow: 
```
from pytriqs.archive import HDFArchive
# load G_tau from h5
h5 = HDFArchive('svo_filename.h5','r') 
# this will show you the content
print h5['DMFT_results']
# loading the desired Gtau, this is is just for me, you have to check what is inside your h5
G_tau = h5['DMFT_results']['it_40']['Gimp_tau_0']
```
Then you can set and run maxent for example as follow:
```
tm_bryan = TauMaxEnt(cost_function='bryan', probability='normal')
# this will set the just loaded Gtau, this is just the spin up block and the first orbital!
tm_bryan.set_G_tau(G_tau['up_0'][0,0].real)

tm_bryan.omega = HyperbolicOmegaMesh(omega_min=-15, omega_max=15, n_points=400)
# this is also just a suggestion, play around with the alpha values
tm_bryan.alpha_mesh = LogAlphaMesh(alpha_min=5e-5, alpha_max=500, n_points=20)
# careful about setting the error!
tm_bryan.set_error(1.e-2)

# run it
tm_bryan_res = tm_bryan.run()
```
after this you can follow with the post-processing and plotting as described in the tutorial. 

Best,
Alex

**Comment by Reyhanehe** [comment]
Dear Alex
than you very much for your very useful comment to solving my problem.
yes I have a "case.h5" file and in this file I have the below contents:
"[u'Delta_tau', u'G_0', u'G_iw', u'G_tau', u'Sigma_iw', u'dft_input', u'dft_misc_input', u'dft_parproj_input', u'dft_symmcorr_input', u'dft_symmpar_input', u'dft_transp_input', u'user_data']"
But because I am a beginner programmer I can not understand the mean of "G_tau=h5['DMFT_results][it_40][Gimp_tau_0]"
sorry, can you explain me more a bout this line?
I used in my "DFT+DMF" calculation the below lines:
" ar = HDFArchive(dft_filename +'.h5','a')
        ar['G_tau'] = S.G_tau"
so the "DMFT_results" that you write in the last line is "G_tau" for me or not?It is "case.h5" file?
and whats the meaning of 40 and 0 in "[it_40][Gimp_tau_0]"
thans so much

**Comment by the-hampel** [comment]
Hi,
yes - so for you the line would just be 
```
G_tau = h5['G_tau']
```
if I understood the structure of your h5 file correctly. the it_40 refers to the 40th DMFT iteration, that I saved as it_40. Nothing import for you ;-)

**Comment by Reyhanehe** [comment]
Dear Alex
Thanks so much.
It works :))
Best,
Reyhaneh
