### ISSUE TITLE
res is not defined!

### ISSUE THREAD

**Issue by Reyhanehe** [TRIQS/maxent#7]

**Comment by Reyhanehe** [comment]
Dear all
Hi
I want to run case_analyser.py. But when I do it I have the below error  that:
"res is not defined"
for solving it, I use "tm.res" in my test. After it I did not have the former error and my run is done.
Is my solution true or I should use another solution for this subject?
Thsnks a lot for any comment on my error
Reyhaneh

**Comment by mzingl** [comment]
What file in the documentation are you referring to? srvo3_analysis.py?
If yes, you need to run the srvo3_run.py first in the SAME script.
These are just examples showing how to use the code.

**Comment by Reyhanehe** [comment]
Dear Mzingl
Thanks for your comment.
Yes I use from this file and then run srvo3_analysis.py But when I want run case_analysis.py I have the error that "res is not defined".
But replacing "tm.res" can solve this problem.Is my solution true?
Thanks so much
