### ISSUE TITLE
S_w

### ISSUE THREAD

**Issue by Reyhanehe** [TRIQS/maxent#8]
Dear All
Hi
I have a question. After using "maxent"In my "case.h5" and in it's group isc I have S_w. How can I use S_w in my cas.py.
I wrote the below program but I have the error that:NameError: name 'S_w' is not defined

"with HDFArchive('case.h5', 'r') as ar:
S_w = ar['isc']['S_w']"
Can you please help me to solve this problem.
Thanks a lot.
Reyhaneh

**Comment by mzingl** [comment]
``` python
with HDFArchive('case.h5', 'r') as ar:
    isc = ar['isc']
S_w = isc.S_w
```

**Comment by Reyhanehe** [comment]
Dear Mzingl
It works, so I clise this issue now.
Thank you very much .
Reyhaneh
